### ISSUE TITLE
Get list of all possibles transitions or events

### ISSUE THREAD

**Issue by bragovo** [amatsuda/stateful_enum#42]
How to get all available transitions or events of current state? I want to add buttons dynamically.

Something like `@foo.transitions` or `@foo.events`

At current moment I get events like this: `@foo.methods.select{ |m| m.to_s.end_with?('_transition') }.map{ |m| m.to_s.sub('_transition', '').to_sym }.select{ |e| @foo.send("can_#{e}?") }`

**Comment by amatsuda** [comment]
Currently it's not possible because the gem doesn't store the given information inside the model.
I did so by design because the implementation looked much cooler.

I understand your use case now, and I actually hit such use case myself, so maybe it's time to add that feature (with some ugliness) to the codebase.

I'd work on it when I had time, or patches are always welcome.

**Comment by amatsuda** [comment]
@bragovo Just added a simple inspection feature that returns the list of possible events and states.
Documentation: https://github.com/amatsuda/stateful_enum#inspecting-all-defined-events-and-current-possible-events
Tests: https://github.com/amatsuda/stateful_enum/blob/master/test/state_inspection_test.rb

Would this work for you? Feedbacks are welcome!

**Comment by bragovo** [comment]
@amatsuda thanks you. This works only for last defined state machine? I have model with two enums and `possible_events` return events only for last.

**Comment by amatsuda** [comment]
@bragovo Thank you very much for a perfect feedback! And I'm so sorry for not being able to come back to this issue sooner.
Just addressed the two enums problem, and published a new gem versioned 0.6.0 with this feature.
Thank you!!
